# Generated by Django 4.0.6 on 2022-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=50)),
                ('todo_description', models.TextField()),
                ('todo_length', models.IntegerField()),
            ],
        ),
    ]
