# Generated by Django 4.0.6 on 2022-07-27 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_length',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
