# Generated by Django 4.0.6 on 2022-07-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0002_remove_todo_todo_length_todo_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_date',
        ),
    ]
