# Generated by Django 4.0.6 on 2022-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0003_remove_todo_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_len',
            field=models.IntegerField(default=60),
        ),
    ]
