# Generated by Django 4.0.6 on 2022-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0004_todo_todo_len'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_len',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
