# Generated by Django 4.0.6 on 2022-08-08 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0011_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
