# Generated by Django 4.0.6 on 2022-08-08 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0013_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, choices=[('today', datetime.date(2022, 8, 8)), ('tomorrow', datetime.date(2022, 8, 9)), ('two_days_later', datetime.date(2022, 8, 10)), ('two_days_later', datetime.date(2022, 8, 11)), ('two_days_later', datetime.date(2022, 8, 12)), ('two_days_later', datetime.date(2022, 8, 13)), ('two_days_later', datetime.date(2022, 8, 14))], default=datetime.date.today),
        ),
    ]
