# Generated by Django 4.0.6 on 2022-08-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0016_alter_todo_date_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high'), ('very high', 'very high')], default='normal'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(),
        ),
    ]
