# Generated by Django 4.0.6 on 2022-08-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0018_alter_todo_date_alter_todo_priority_alter_todo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('-', '-'), ('work', 'work')], default='-', max_length=100)),
            ],
        ),
    ]
