# Generated by Django 4.0.6 on 2022-08-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0019_todocatagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocatagory',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
