# Generated by Django 4.0.6 on 2022-08-12 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_logged_in_app', '0020_alter_todocatagory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todocatagory',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(choices=[(datetime.date(2022, 8, 12), datetime.date(2022, 8, 12)), (datetime.date(2022, 8, 13), datetime.date(2022, 8, 13)), (datetime.date(2022, 8, 14), datetime.date(2022, 8, 14)), (datetime.date(2022, 8, 15), datetime.date(2022, 8, 15)), (datetime.date(2022, 8, 16), datetime.date(2022, 8, 16)), (datetime.date(2022, 8, 17), datetime.date(2022, 8, 17)), (datetime.date(2022, 8, 18), datetime.date(2022, 8, 18))], default=datetime.date.today),
        ),
    ]
