# Generated by Django 4.0.6 on 2022-08-15 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0021_todocatagory_creator_alter_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='catagory',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_logged_in_app.todocatagory'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(choices=[(datetime.date(2022, 8, 15), datetime.date(2022, 8, 15)), (datetime.date(2022, 8, 16), datetime.date(2022, 8, 16)), (datetime.date(2022, 8, 17), datetime.date(2022, 8, 17)), (datetime.date(2022, 8, 18), datetime.date(2022, 8, 18)), (datetime.date(2022, 8, 19), datetime.date(2022, 8, 19)), (datetime.date(2022, 8, 20), datetime.date(2022, 8, 20)), (datetime.date(2022, 8, 21), datetime.date(2022, 8, 21))], default=datetime.date.today),
        ),
    ]
