# Generated by Django 4.0.6 on 2022-08-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0022_todo_catagory_alter_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='catagory',
        ),
    ]
