# Generated by Django 4.0.6 on 2022-08-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0023_remove_todo_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='catagory',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_logged_in_app.todocatagory'),
        ),
    ]
