# Generated by Django 4.0.6 on 2022-08-15 13:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_logged_in_app', '0024_todo_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoCatagory',
            new_name='TodoCategory',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
