# Generated by Django 4.0.6 on 2022-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0026_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.TextField(blank=True, choices=[('very_low', 'Very low'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('very_high', 'Very high')], null=True),
        ),
    ]
