# Generated by Django 4.0.6 on 2022-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0028_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
