# Generated by Django 4.0.6 on 2022-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0030_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
