# Generated by Django 4.0.6 on 2022-08-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0031_todo_priority_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority_num',
        ),
    ]
