# Generated by Django 4.0.6 on 2022-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_logged_in_app', '0032_remove_todo_priority_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
